version: "2"
services:
 web:
    build: .
    image: users_web
    ports:
    - "3000:3000"
    depends_on:
      - mongo
    networks:
      - shared
 mongo:
    image: mongo
    networks:
    - shared
    ports:
      - "27017:27017"
networks:
  shared:
    external: true